#!/bin/sh -eu

export LC_ALL=C

repo="$(realpath /ALT/repo/sisyphus/release/latest)"

tmpdir=
cleanup_tmpdir()
{
	[ -z "$tmpdir" ] || rm -rf -- "$tmpdir"
	exit "$@"
}

tmpdir=$(mktemp -dt "${0##*/}.XXXXXXXX")
trap 'cleanup_tmpdir $?' EXIT
trap 'exit 143' HUP INT QUIT PIPE TERM

[ "$#" -ge 1 ] || {
	echo "Usage: $0 <source_package ...>"
	exit 1
}

printf '%s\n' "$@" > "$tmpdir"/rm-sname
sort -u -o "$tmpdir"/rm-sname{,}
join "$repo"/files/list/src.list "$tmpdir"/rm-sname -o 1.3 \
	> "$tmpdir"/rm-src
cat "$tmpdir"/rm-src

arches=x86_64
comps=classic
noarch_comps=classic

for a in noarch $arches; do
	mkdir "$tmpdir/$a"
	rsync -rltp "$repo/$a"/base.bloat/ "$tmpdir/$a"/base/
	for c in "$tmpdir/$a"/base/pkglist.*; do
		compname="${c##*.}"
		mkdir "$tmpdir/$a/RPMS.$compname"
		pkglist-query "$compname\t%{sourcerpm}\t%{NVRA}.rpm\n" "$c"
	done > "$tmpdir"/all-comp-src-bin
	sort -k2,2 -o "$tmpdir"/all-comp-src-bin{,}
	join -1 2 "$tmpdir"/all-comp-src-bin "$tmpdir"/rm-src -t $'\t' -o '1.1 1.2 1.3' \
		> "$tmpdir"/rm-name-src-bin
	sort -o "$tmpdir"/rm-name-src-bin{,}
	echo "removing ($a):"
	echo  =============
	cat "$tmpdir"/rm-name-src-bin
	echo  =============
 	genbasedir \
		--maybe-unchanged \
		--bloat \
		--patch-basedir \
		--rm-list "$tmpdir"/rm-name-src-bin \
		--topdir "$tmpdir" \
		--no-bz2 --no-xz \
		"$a"
done

for a in $arches; do
	cat > "$tmpdir/$a.list" <<-EOF
	rpm file:$tmpdir $a classic
	rpm file:$tmpdir noarch classic
	EOF
	echo "unmets in $a:"
	unmets -a "$a" -s "$tmpdir/$a.list"
done
